// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPSIZdXSf7r1VV5TTMfSzQDtH19sjdH2w',
    appId: '1:497896991650:web:bc4f035451ea8c7119a0fb',
    messagingSenderId: '497896991650',
    projectId: 'quotely-7c192',
    authDomain: 'quotely-7c192.firebaseapp.com',
    storageBucket: 'quotely-7c192.firebasestorage.app',
    measurementId: 'G-PGLRYEXQQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaQjICO-jAQhO964YDSB4aPwzKOK4YsLk',
    appId: '1:497896991650:android:f4ac4dd4c3dd949919a0fb',
    messagingSenderId: '497896991650',
    projectId: 'quotely-7c192',
    storageBucket: 'quotely-7c192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt0m7KKOSnwbhzBfmrgQJupKanyWhjKm4',
    appId: '1:497896991650:ios:d1d74ee86837018319a0fb',
    messagingSenderId: '497896991650',
    projectId: 'quotely-7c192',
    storageBucket: 'quotely-7c192.firebasestorage.app',
    iosBundleId: 'com.example.graduationProjectNti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt0m7KKOSnwbhzBfmrgQJupKanyWhjKm4',
    appId: '1:497896991650:ios:d1d74ee86837018319a0fb',
    messagingSenderId: '497896991650',
    projectId: 'quotely-7c192',
    storageBucket: 'quotely-7c192.firebasestorage.app',
    iosBundleId: 'com.example.graduationProjectNti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPSIZdXSf7r1VV5TTMfSzQDtH19sjdH2w',
    appId: '1:497896991650:web:f9cf7f713737507319a0fb',
    messagingSenderId: '497896991650',
    projectId: 'quotely-7c192',
    authDomain: 'quotely-7c192.firebaseapp.com',
    storageBucket: 'quotely-7c192.firebasestorage.app',
    measurementId: 'G-JR1J2GZTWC',
  );
}
